# Generated by Django 5.2.4 on 2025-07-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetups", "0005_meetup_date_meetup_organizer_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetup",
            name="participants",
            field=models.ManyToManyField(to="meetups.participant"),
        ),
    ]
